services:
  - type: web
    name: krazy-kanban
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    rootDir: Develop
    envVars:
      - key: NODE_VERSION
        value: 20
